export const SET_CAROUSEL = "SET_CAROUSEL";

export const SET_DANH_SACH_PHIM = "SET_DANH_SACH_PHIM";

export const SET_PHIM_DANG_CHIEU = "SET_PHIM_DANG_CHIEU";

export const SET_PHIM_SAP_CHIEU = "SET_PHIM_SAP_CHIEU";

export const SET_HE_THONG_RAP_CHIEU = "SET_HE_THONG_RAP_CHIEU";

export const SET_CHI_TIET_PHIM = "SET_CHI_TIET_PHIM";

export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";

export const SET_CHI_TIET_PHONG_VE = "SET_CHI_TIET_PHONG_VE";

export const DAT_VE = "DAT_VE";

export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";

export const DISPLAY_LOADING = "DISPLAY_LOADING";

export const HIDE_LOADING = "HIDE_LOADING";

export const DAT_VE_HOAN_TAT = "DAT_VE_HOAN_TAT";

export const CHUYEN_TAB = "CHUYEN_TAB";

export const CHANGE_TAB_ACTIVE = "CHANGE_TAB_ACTIVE";



